In [8]:
import numpy as np

In [43]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [6]:
b = np.array([1,"sdfg",3.34])
print(b)

['1' 'sdfg' '3.34']


In [13]:
c = np.array([[1.543,345.53,3.344],[54.54,76.98,9876.65784]])
print(c)

[[1.54300000e+00 3.45530000e+02 3.34400000e+00]
 [5.45400000e+01 7.69800000e+01 9.87665784e+03]]


In [15]:
d = np.array([[1,2,3,4],[5,6,7,8]])
print(d)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
#Get Dimensions
a.ndim

1

In [17]:
b.ndim

2

In [19]:
print(c.ndim)
print(d.ndim)

2
2


In [21]:
#get shape
a.shape

(3,)

In [23]:
b.shape

(2, 3)

In [24]:
#get Data type
a.dtype

dtype('int64')

In [36]:
e = np.array([1,2,3],dtype='int16')
print(e)
e.dtype

[1 2 3]


dtype('int16')

In [44]:
#get size
a.itemsize

2

In [48]:
#Get TOTAL SIZE
a.size * a.itemsize

6

In [49]:
b.size * b.itemsize

48

In [52]:
a.nbytes


6

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]],dtype='int16')
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [61]:
a.shape

(2, 7)

In [62]:
#Get The specific element [r,c]
a[0, 5]

np.int16(6)

In [64]:
a[1,-2]

np.int16(13)

In [68]:
#Get a specific ROW
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14], dtype=int16)

In [72]:
#Get a specific COLUMNS
a[:,2]

array([ 3, 10], dtype=int16)

In [77]:
#GETTING MORE FANCY
a[1,2:7:1]

array([10, 11, 12, 13, 14], dtype=int16)

In [78]:
#change a specific array elemenr
a[1,5] =20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [79]:
a[:,2] =5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [81]:
# 3D
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [84]:
#Get the specific element in 3D
b[0,1,1]

np.int64(4)

In [10]:
#Initalizing different types of arrays
#all 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
np.zeros((2,3,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [15]:
#1s Matrix
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.ones((5,4),dtype="int16")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [18]:
# any number matrix
np.full((2,2) ,99)

array([[99, 99],
       [99, 99]])

In [20]:
# full_like
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]], dtype=int16)

In [21]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [23]:
# random decimal number
np.random.rand(4,3)

array([[0.23746   , 0.89507193, 0.02544101],
       [0.24869681, 0.86577634, 0.82704562],
       [0.2756335 , 0.42682936, 0.22984354],
       [0.60002861, 0.48679566, 0.18285969]])

In [24]:
# random  sample decimal number
np.random.random_sample(a.shape)

array([[0.36086892, 0.64240254, 0.47418024, 0.18889732, 0.81525473,
        0.32315166, 0.60524786],
       [0.02590292, 0.35512844, 0.29044606, 0.72941645, 0.07709356,
        0.67789169, 0.37290344]])

In [25]:
#random  sample integer number
np.random.randint(4,8,(3,3))

array([[4, 7, 7],
       [6, 7, 5],
       [6, 6, 4]], dtype=int32)

In [26]:
np.random.randint(4,8,(3,3))

array([[7, 6, 5],
       [7, 5, 7],
       [6, 5, 4]], dtype=int32)

In [27]:
np.random.randint(4,8,(3,3))

array([[6, 7, 4],
       [7, 5, 7],
       [6, 5, 7]], dtype=int32)

In [34]:
#For Identity Matrix
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [42]:
#Repeat
arr = np.array([[1,2,3]])
r1= np.repeat(arr,3,axis =0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [53]:
#PROBLEM SOLUTION

output = np.ones([5,5],dtype="int16")
print(output)
z = np.zeros([3,3],dtype="int16")
z[1,1] = 9
print(z)
output[1:4,1:4]=z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [58]:
a = np.array([1,2,3])
b=a.copy()
b[0]=1000
print(b)
print(a)

[1000    2    3]
[1 2 3]


MATHEMATICS

In [73]:
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [63]:
a+2

array([3, 4, 5, 6])

In [64]:
a-4

array([-3, -2, -1,  0])

In [65]:
a*9

array([ 9, 18, 27, 36])

In [66]:
a/5

array([0.2, 0.4, 0.6, 0.8])

In [67]:
a//3

array([0, 0, 1, 1])

In [68]:
a%3

array([1, 2, 0, 1])

In [74]:
print(a)

[1 2 3 4]


In [75]:
b = np.array([1,0,1,0])
print(b)

[1 0 1 0]


In [76]:
b + a

array([2, 2, 4, 4])

In [77]:
a**2

array([ 1,  4,  9, 16])

In [81]:
#Taking Sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [82]:
np.sin(b)

array([0.84147098, 0.        , 0.84147098, 0.        ])

In [89]:
#Taking cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [90]:
#Taking tan
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [91]:
#only sin cos and tan

LINEAR ALGEBRA

In [102]:
a =np.ones((2,3))
print(a)
b =np.full((3,2),9)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[9 9]
 [9 9]
 [9 9]]


In [98]:
a*b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [103]:
np.matmul(a,b)

array([[27., 27.],
       [27., 27.]])

In [101]:
a =np.ones((2,4))
print(a)
b =np.full((3,2),9)
print(b)
np.matmul(a,b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[9 9]
 [9 9]
 [9 9]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [106]:
#find the determinants
c =np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [108]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
np.min(stats)

np.int64(1)

In [111]:
np.min(stats,axis=0)

array([1, 2, 3])

In [113]:
np.min(stats,axis=1)

array([1, 4])

In [114]:
np.max(stats)

np.int64(6)

In [115]:
np.sum(stats)

np.int64(21)

REORGANIZING ARRAYS

In [122]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape(8,1)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [127]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [129]:
#vertical stacking
v1=np.array([1,2,3])
v2=np.array([4,5,6])
np.vstack([v1,v2])

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
#Horizontal stacking
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [137]:
#Load data from files
filedata = np.genfromtxt(r"C:\Users\sarva\Downloads\data.txt",delimiter=",")
filedata
filedata = filedata.astype("int32")
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [140]:
###Advance indexing and boolean masking
filedata >50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [141]:
filedata [filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [142]:
#you can index with list in numpy
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [144]:
a[[1,2,6]]

array([2, 3, 7])

In [145]:
np.any(filedata>50,axis=0) #axis=0(vertically check)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [147]:
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [150]:
((filedata>50) & (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [151]:
~((filedata>50) & (filedata<100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])